// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckLocalizationExists(arg1:string):Promise<boolean>;

export function CompareINIFiles(arg1:string,arg2:string):Promise<Array<main.INIKeyValue>>;

export function CompareINIFilesDetailed(arg1:string,arg2:string):Promise<main.CompareResult>;

export function CreateLocalizationDir(arg1:string):Promise<void>;

export function DetectStarCitizenPath():Promise<string>;

export function DownloadAndInstallLocalization(arg1:string,arg2:string):Promise<string>;

export function ExportLocaleFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExportLocaleFileStripped(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetCurrentLocaleINIPath(arg1:string):Promise<string>;

export function GetLocalizationPath(arg1:string):Promise<string>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function GetUserLanguage(arg1:string):Promise<string>;

export function HasLocalizationBase(arg1:string):Promise<boolean>;

export function ImportLocaleFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ListInstalledLocalizations(arg1:string):Promise<Array<string>>;

export function ReadINIFile(arg1:string):Promise<Array<main.INIKeyValue>>;

export function ResetToDefaultLanguage(arg1:string):Promise<void>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SaveTextFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectDirectory():Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function SetUserLanguage(arg1:string,arg2:string):Promise<string>;

export function UpdateINIFile(arg1:string,arg2:string,arg3:Array<main.INIKeyValue>):Promise<void>;

export function ValidateStarCitizenPath(arg1:string):Promise<boolean>;

export function WriteINIFile(arg1:string,arg2:Array<main.INIKeyValue>):Promise<void>;
