// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckLocalizationExists(arg1:string):Promise<boolean>;

export function CreateLocalizationDir(arg1:string):Promise<void>;

export function DetectStarCitizenPath():Promise<string>;

export function DownloadAndInstallLocalization(arg1:string,arg2:string):Promise<string>;

export function GetLocalizationPath(arg1:string):Promise<string>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function GetUserLanguage(arg1:string):Promise<string>;

export function HasLocalizationBase(arg1:string):Promise<boolean>;

export function ListInstalledLocalizations(arg1:string):Promise<Array<string>>;

export function ResetToDefaultLanguage(arg1:string):Promise<void>;

export function SelectDirectory():Promise<string>;

export function SetUserLanguage(arg1:string,arg2:string):Promise<string>;

export function ValidateStarCitizenPath(arg1:string):Promise<boolean>;
