// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyActiveVehicleOrderToLocale(arg1, arg2) {
  return window['go']['main']['App']['ApplyActiveVehicleOrderToLocale'](arg1, arg2);
}

export function ApplyLocalLocaleToGame(arg1, arg2) {
  return window['go']['main']['App']['ApplyLocalLocaleToGame'](arg1, arg2);
}

export function BuildOrderedLocaleToTemp(arg1, arg2) {
  return window['go']['main']['App']['BuildOrderedLocaleToTemp'](arg1, arg2);
}

export function CheckLocalizationExists(arg1) {
  return window['go']['main']['App']['CheckLocalizationExists'](arg1);
}

export function CompareINIFiles(arg1, arg2) {
  return window['go']['main']['App']['CompareINIFiles'](arg1, arg2);
}

export function CompareINIFilesDetailed(arg1, arg2) {
  return window['go']['main']['App']['CompareINIFilesDetailed'](arg1, arg2);
}

export function CreateLocalizationDir(arg1) {
  return window['go']['main']['App']['CreateLocalizationDir'](arg1);
}

export function DeleteLocalization(arg1, arg2) {
  return window['go']['main']['App']['DeleteLocalization'](arg1, arg2);
}

export function DeleteVehicleOrderSave(arg1, arg2) {
  return window['go']['main']['App']['DeleteVehicleOrderSave'](arg1, arg2);
}

export function DetectStarCitizenPath() {
  return window['go']['main']['App']['DetectStarCitizenPath']();
}

export function DownloadAndInstallLocalization(arg1, arg2) {
  return window['go']['main']['App']['DownloadAndInstallLocalization'](arg1, arg2);
}

export function DownloadToTemp(arg1, arg2) {
  return window['go']['main']['App']['DownloadToTemp'](arg1, arg2);
}

export function EnsureSortDirs(arg1) {
  return window['go']['main']['App']['EnsureSortDirs'](arg1);
}

export function ExportLocaleFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportLocaleFile'](arg1, arg2, arg3);
}

export function ExportLocaleFileStripped(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportLocaleFileStripped'](arg1, arg2, arg3);
}

export function ExportVehicleOrderFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportVehicleOrderFile'](arg1, arg2, arg3);
}

export function GetActiveVehicleOrder(arg1) {
  return window['go']['main']['App']['GetActiveVehicleOrder'](arg1);
}

export function GetCurrentLocaleINIPath(arg1) {
  return window['go']['main']['App']['GetCurrentLocaleINIPath'](arg1);
}

export function GetLocalLocaleINIPath(arg1) {
  return window['go']['main']['App']['GetLocalLocaleINIPath'](arg1);
}

export function GetLocalizationPath(arg1) {
  return window['go']['main']['App']['GetLocalizationPath'](arg1);
}

export function GetSortBasePath(arg1) {
  return window['go']['main']['App']['GetSortBasePath'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetUserLanguage(arg1) {
  return window['go']['main']['App']['GetUserLanguage'](arg1);
}

export function HasLocalizationBase(arg1) {
  return window['go']['main']['App']['HasLocalizationBase'](arg1);
}

export function ImportLocaleFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportLocaleFile'](arg1, arg2, arg3);
}

export function ImportVehicleOrderFile(arg1, arg2) {
  return window['go']['main']['App']['ImportVehicleOrderFile'](arg1, arg2);
}

export function InstallLocaleFromFileElevated(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallLocaleFromFileElevated'](arg1, arg2, arg3);
}

export function ListInstalledLocalizations(arg1) {
  return window['go']['main']['App']['ListInstalledLocalizations'](arg1);
}

export function ListVehicleOrderSaves(arg1) {
  return window['go']['main']['App']['ListVehicleOrderSaves'](arg1);
}

export function ReadINIFile(arg1) {
  return window['go']['main']['App']['ReadINIFile'](arg1);
}

export function ResetToDefaultLanguage(arg1) {
  return window['go']['main']['App']['ResetToDefaultLanguage'](arg1);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SaveLocalLocaleFromFile(arg1, arg2) {
  return window['go']['main']['App']['SaveLocalLocaleFromFile'](arg1, arg2);
}

export function SaveTextFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveTextFile'](arg1, arg2, arg3);
}

export function SaveVehicleOrderActive(arg1, arg2) {
  return window['go']['main']['App']['SaveVehicleOrderActive'](arg1, arg2);
}

export function SaveVehicleOrderAs(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveVehicleOrderAs'](arg1, arg2, arg3);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectJSONFile(arg1) {
  return window['go']['main']['App']['SelectJSONFile'](arg1);
}

export function SetActiveVehicleOrderByName(arg1, arg2) {
  return window['go']['main']['App']['SetActiveVehicleOrderByName'](arg1, arg2);
}

export function SetUserLanguage(arg1, arg2) {
  return window['go']['main']['App']['SetUserLanguage'](arg1, arg2);
}

export function StripActiveVehicleOrderFromLocale(arg1, arg2) {
  return window['go']['main']['App']['StripActiveVehicleOrderFromLocale'](arg1, arg2);
}

export function UpdateINIFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateINIFile'](arg1, arg2, arg3);
}

export function ValidateStarCitizenPath(arg1) {
  return window['go']['main']['App']['ValidateStarCitizenPath'](arg1);
}

export function WriteINIFile(arg1, arg2) {
  return window['go']['main']['App']['WriteINIFile'](arg1, arg2);
}
